### ISSUE TITLE
建议添加：抬棺曲

### ISSUE THREAD

**Issue by Latomoyocarl** [oruyanke/fubuki-button#10]
添加原因：不用说，加到狐歌吧。

[astronomia fubukidance](https://www.bilibili.com/video/BV1i54y197K2)

**Comment by lonelyion** [comment]
过几天加，最近有点忙

**Comment by lonelyion** [comment]
Added in commit 73995729ae3f0e74720caf53083c8de7f00ebc03

因为原视频时间有点长所以截了前一分钟
